common/models/WebSite.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "web_site".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property string $link
 * @property integer $category_id
 * @property integer $rate
 * @property integer $view
 * @property integer $creator_id
 *
 * @property User $creator
 */
class WebSite extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    public $main_image = 1;

    public static function tableName() {
        return 'web_site';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['title', 'description', 'link', 'category_id', 'creator_id'], 'required'],
            [['category_id', 'rate', 'view', 'creator_id'], 'integer'],
            [['title', 'description', 'link'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'link' => 'Link',
            'category_id' => 'Category ID',
            'rate' => 'Rate',
            'view' => 'View',
            'creator_id' => 'Creator ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreator() {
        return $this->hasOne(User::className(), ['id' => 'creator_id']);
    }

    public function getImage() {

        return $this->hasMany(WebSiteGallery::className(), ['site_id' => 'id']);
    }

    public function getCategory() {

        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }
    public function getRelatedSites() {

        return $this->hasMany(WebSite::className(), ['category_id' => 'category_id']);

    }

    public function getImageBasePath() {


        return __DIR__ . '/../../images/';
        
    }

    

    public function getRates() {
        return $this->hasMany(Rates::className(), ['site_id' => 'id']);
    }
    
  

}

backend/controllers/WebSiteController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\WebSite;
use app\models\SearchWebSite;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * WebSiteController implements the CRUD actions for WebSite model.
 */
class WebSiteController extends BaseController {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all WebSite models.
     * @return mixed
     */
    public function actionIndex() {
//        $imagesPath = ;

        $searchModel = new SearchWebSite();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $siteModel = new WebSite;

        $imagesPath = $siteModel->getImageBasePath();
       
        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                    'imagesPath' => Yii::getAlias('@uploads_path'),
        ]);
    }

    /**
     * Displays a single WebSite model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new WebSite model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new WebSite();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing WebSite model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);
        $galleryModel = WebSiteGallery::findAll(["site_id" => $id]);
        if (!\Yii::$app->user->isGuest && \Yii::$app->user->identity->id == $model->creator_id) {
            $categoryModel = Category::find()->all();
            if ($galleryModel == null) {
                $galleryModel = new WebSiteGallery();
            }
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                if (Yii::$app->request->post()["WebSiteGallery"]) {


                    $uploadedImages = json_decode(Yii::$app->request->post()["WebSiteGallery"]["uploadedFiles"]);
                    $deletedImages = json_decode(Yii::$app->request->post()["WebSiteGallery"]["deletedFiles"]);
                    $deleteUploadedImages = json_decode(Yii::$app->request->post()["WebSiteGallery"]["deleteUploadedImages"]);

                    if ($deletedImages != null) {
                        foreach ($deletedImages as $deletedImage) {
                            unlink($deletedImage->targetFile);
                        }
                    }
                    if ($deleteUploadedImages != null) {
                        foreach ($deleteUploadedImages as $deleteUploadedImage) {
                            WebSiteGallery::deleteAll(["id" => $deleteUploadedImage->id]);
                            unlink($_SERVER['DOCUMENT_ROOT'] . "uploads/web_site_images/" . $deleteUploadedImage->image);
                        }
                    }
                    if ($uploadedImages != null) {
                        foreach ($uploadedImages as $uploadedImage) {

                            $image = new WebSiteGallery();
                            $image->site_id = $id;
                            $image->image = $uploadedImage->fileName;
                            rename($uploadedImage->targetFile, $_SERVER['DOCUMENT_ROOT'] . "uploads/web_site_images/" . $uploadedImage->fileName);

                            $image->save();
                        }
                    }
                    $mainImage = Yii::$app->request->post()["WebSiteGallery"]["mainImage"];
                    $siteMainImage = WebSiteGallery::find()->where(['image' => $mainImage])->one();
//                var_dump($mainImageId);die;
                    if ($siteMainImage) {

                        $siteMainImage->main = 1;
                        $siteMainImage->save();
                    }
                }
                return $this->redirect(['view', 'id' => $model->id, 'categoryModel' => $categoryModel]);
            } else {
                return $this->render('update', [
                            'model' => $model,
                            'categoryModel' => $categoryModel,
                            'galleryModel' => $galleryModel
                ]);
            }
        } else {
            return $this->redirect(\Yii::$app->urlManager->createUrl('site/index'));
        }
    }

    /**
     * Deletes an existing WebSite model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the WebSite model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return WebSite the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = WebSite::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

frontend/controllers/WebSiteController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\WebSite;
use common\models\Category;
use common\models\WebSiteGallery;
use common\models\Rates;
use app\models\SearchWebSite;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * WebSiteController implements the CRUD actions for WebSite model.
 */
class WebSiteController extends BaseController {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
//                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all WebSite models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new SearchWebSite();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }
    public function actionList() {
        $searchModel = new SearchWebSite();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single WebSite model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new WebSite model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new WebSite();
        $galleryModel = new WebSiteGallery();
        $categoryModel = Category::find()->all();
        $model->creator_id = \Yii::$app->user->identity->id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $galleryModel->site_id = $model->id;
            if ($galleryModel->load(Yii::$app->request->post())) {
                $uploadedImages = json_decode(Yii::$app->request->post("WebSiteGallery")["uploadedFiles"]);
                $deletedImages = json_decode(Yii::$app->request->post("WebSiteGallery")["deletedFiles"]);
                if ($deletedImages != null) {
                    foreach ($deletedImages as $deletedImage) {
                        unlink($deletedImage->targetFile);
                    }
                }
                if ($uploadedImages != null) {
                    foreach ($uploadedImages as $uploadedImage) {
                        $newImage = new WebSiteGallery();
                        $newImage->site_id = $model->id;
                        $newImage->image = $uploadedImage->fileName;

                        rename($uploadedImage->targetFile, $_SERVER['DOCUMENT_ROOT'] . "frontend/web/uploads/web_site_images/" . $uploadedImage->fileName);
                        $newImage->save();
                    }
                }
                $mainImage = Yii::$app->request->post()["WebSiteGallery"]["mainImage"];
                $siteMainImage = WebSiteGallery::find()->where(['image' => $mainImage])->one();
                if ($siteMainImage) {
                    $siteMainImage->main = 1;
                    $siteMainImage->save();
                }
            }
            return $this->redirect(['view', 'id' => $model->id, 'galleryModel' => $galleryModel]);
        } else {
            return $this->render('create', [
                        'model' => $model,
                        'categoryModel' => $categoryModel,
                        'galleryModel' => $galleryModel
            ]);
        }
    }

    /**
     * Updates an existing WebSite model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);
        $galleryModel = WebSiteGallery::findAll(["site_id" => $id]);
        if (!\Yii::$app->user->isGuest && \Yii::$app->user->identity->id == $model->creator_id) {
            $categoryModel = Category::find()->all();
            if ($galleryModel == null) {
                $galleryModel = new WebSiteGallery();
            }
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                if (Yii::$app->request->post()["WebSiteGallery"]) {


                    $uploadedImages = json_decode(Yii::$app->request->post()["WebSiteGallery"]["uploadedFiles"]);
                    $deletedImages = json_decode(Yii::$app->request->post()["WebSiteGallery"]["deletedFiles"]);
                    $deleteUploadedImages = json_decode(Yii::$app->request->post()["WebSiteGallery"]["deleteUploadedImages"]);

                    if ($deletedImages != null) {
                        foreach ($deletedImages as $deletedImage) {
                            unlink($deletedImage->targetFile);
                        }
                    }
                    if ($deleteUploadedImages != null) {
                        foreach ($deleteUploadedImages as $deleteUploadedImage) {
                            WebSiteGallery::deleteAll(["id" => $deleteUploadedImage->id]);
                            unlink($_SERVER['DOCUMENT_ROOT'] . "frontend/web/uploads/web_site_images/" . $deleteUploadedImage->image);
                        }
                    }
                    if ($uploadedImages != null) {
                        foreach ($uploadedImages as $uploadedImage) {

                            $image = new WebSiteGallery();
                            $image->site_id = $id;
                            $image->image = $uploadedImage->fileName;
                            rename($uploadedImage->targetFile, $_SERVER['DOCUMENT_ROOT'] . "uploads/web_site_images/" . $uploadedImage->fileName);

                            $image->save();
                        }
                    }
                    $mainImage = Yii::$app->request->post()["WebSiteGallery"]["mainImage"];
                    $siteMainImage = WebSiteGallery::find()->where(['image' => $mainImage])->one();
//                var_dump($mainImageId);die;
                    if ($siteMainImage) {

                        $siteMainImage->main = 1;
                        $siteMainImage->save();
                    }
                }
                return $this->redirect(['view', 'id' => $model->id, 'categoryModel' => $categoryModel]);
            } else {
                return $this->render('update', [
                            'model' => $model,
                            'categoryModel' => $categoryModel,
                            'galleryModel' => $galleryModel
                ]);
            }
        } else {
            return $this->redirect(\Yii::$app->urlManager->createUrl('site/index'));
        }
    }

    public function actionRate() {
        $rateModel = new Rates();
        $site_id = Yii::$app->request->get()['id'];
        if (!\Yii::$app->user->isGuest) {

            $rate = Rates::findAll(["site_id" => Yii::$app->request->get()['id'], "user_id" => \Yii::$app->user->identity->id]);
            if (count($rate) > 0) {
                $rateModel->deleteAll(["site_id" => Yii::$app->request->get()['id'], "user_id" => \Yii::$app->user->identity->id]);
                $result['rated'] = "rate";
            } else {

                $rateModel->user_id = \Yii::$app->user->identity->id;
                $rateModel->site_id = Yii::$app->request->get()['id'];
// 
                $rateModel->save();
                $result['rated'] = "unrate";
            }
            $result['id'] = Yii::$app->request->get()['id'];

        }else{
            $result['isGuest'] = true;
        }
            return json_encode($result);
    }

    /**
     * Deletes an existing WebSite model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $model = $this->findModel($id);

        if (!\Yii::$app->user->isGuest && \Yii::$app->user->identity->id == $model->creator_id) {
            $this->findModel($id)->delete();
            return $this->redirect(['index']);
        } else {
            return $this->redirect(\Yii::$app->urlManager->createUrl('site/index'));
        }
    }

    /**
     * Finds the WebSite model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return WebSite the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = WebSite::findOne($id)) !== null) {

            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

frontend/views/web-site/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\WebSite */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="web-site-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'link') ?>

    <?= $form->field($model, 'category_id') ?>

    <?php // echo $form->field($model, 'rate') ?>

    <?php // echo $form->field($model, 'view') ?>


    <?php // echo $form->field($model, 'creator_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/web-site/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\WebSite */

$this->title = 'Create Web Site';
$this->params['breadcrumbs'][] = ['label' => 'Web Sites', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <div class="row">
        <div class="col-md-offset-2 col-md-8 col-sm-12">
            <div class="web-site-create">

                <h1><?= Html::encode($this->title) ?></h1>

                <?=
                $this->render('_form', [
                    'model' => $model,
                    'categoryModel' => $categoryModel,
                    'galleryModel' => $galleryModel
                ])
                ?>

            </div>
        </div>
    </div>
</div>

frontend/views/web-site/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\WebSite */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Web Sites';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="web-site-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Web Site', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?php // var_dump($dataProvider);die; ?>
    <?php
    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
//            'id',
            [
                'format' => 'html',
                'label' => 'Main Image',
                'contentOptions' => ['class' => ''],
                'value' => function ($data) {
            if ($data['image']['image'] != null) {

                return Html::img('/uploads/web_site_images/' . $data['image']['image'], ['width' => '60px']);
            } else {
//                        sd
                return Html::img('/uploads/web_site_images/no_image.png', ['width' => '60px']);
            }
        },
            ],
            'title',
            'description',
            'link',
//            'category_id',
            'rate',
       
            'category.name',
           
            [
                'format' => 'html',
                'label' => 'Main Image',
                'value' => function ($data) {

                    $rated = 0;
                    foreach ($data['rates'] as $rate) {
                        if (!\Yii::$app->user->isGuest && $rate['user_id'] == \Yii::$app->user->identity->id) {
                            $rated = 1;
                        }
                    }
                    if ($rated == 1) {
                        return Html::a('Unrate', ['web-site/rate', 'id' => $data['id']], [
                                    'class' => 'rate btn btn-danger'
                        ]);
                    } else {
                        return Html::a('Rate', ['web-site/rate', 'id' => $data['id']], ['class' => 'rate btn btn-primary']);
                    }
                },
                    ],
                          [
                'format' => 'html',
                'label' => 'Main Image',
                'value' => function ($data) {

                    
                   return count($data['rates']);
                },
                    ],
                    ['class' => 'yii\grid\ActionColumn'],
                ],
            ]);
            ?>

    <script type="text/javascript">
        $(document).ready(function () {
            $("body").on("click", ".rate", function (event) {
                event.preventDefault();
                var rateClass = "";
                var curSite = $(this);
                if ($(curSite).hasClass("btn-primary")) {
                    rateClass = " rate btn btn-danger";
                } else {
                    rateClass = "rate btn btn-primary";
                }
                $.ajax({
                    url: $(this).attr('href'),
                    method: "GET"
                }).done(function (response) {
                    var result = jQuery.parseJSON(response);
                    if(result.isGuest){
                        alert("please login");
                        return false;
                    };
                    var template = _.template($('#rate_tpl').html())({
                        rateClass: result.rated,
                        siteId: result.id
                    });

                    $(curSite).parent().html(_.template(template));


                }).fail(function () {

                });
            });
        });
                </script>

    <script type = "text/template" id = 'rate_tpl' >
                <a class = "rate btn <%= (rateClass=='rate')?'btn-primary':'btn-danger'%> " href = "/web-site/rate?id=<%= siteId %>" > <%= (rateClass=='rate')?'Rate':'Unrate'%> </a>
    </script>

frontend/views/web-site/list.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\WebSite */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Web Sites';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="web-site-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Web Site', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?php // var_dump($dataProvider);die; ?>
    <?php
    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
//            'id',
            [
                'format' => 'html',
                'label' => 'Main Image',
                'contentOptions' => ['class' => ''],
                'value' => function ($data) {
            if ($data['image']['image'] != null) {

                return Html::img('/uploads/web_site_images/' . $data['image']['image'], ['width' => '60px']);
            } else {
//                        sd
                return Html::img('/uploads/web_site_images/no_image.png', ['width' => '60px']);
            }
        },
            ],
            'title',
            'description',
            'link',
//            'category_id',
            'rate',
       
            'category.name',
           
            [
                'format' => 'html',
                'label' => 'Main Image',
                'value' => function ($data) {

                    $rated = 0;
                    foreach ($data['rates'] as $rate) {
                        if (!\Yii::$app->user->isGuest && $rate['user_id'] == \Yii::$app->user->identity->id) {
                            $rated = 1;
                        }
                    }
                    if ($rated == 1) {
                        return Html::a('Unrate', ['web-site/rate', 'id' => $data['id']], [
                                    'class' => 'rate btn btn-danger'
                        ]);
                    } else {
                        return Html::a('Rate', ['web-site/rate', 'id' => $data['id']], ['class' => 'rate btn btn-primary']);
                    }
                },
                    ],
                          [
                'format' => 'html',
                'label' => 'Main Image',
                'value' => function ($data) {

                    
                   return count($data['rates']);
                },
                    ],
                    ['class' => 'yii\grid\ActionColumn'],
                ],
            ]);
            ?>

    <script type="text/javascript">
        $(document).ready(function () {
            $("body").on("click", ".rate", function (event) {
                event.preventDefault();
                var rateClass = "";
                var curSite = $(this);
                if ($(curSite).hasClass("btn-primary")) {
                    rateClass = " rate btn btn-danger";
                } else {
                    rateClass = "rate btn btn-primary";
                }
                $.ajax({
                    url: $(this).attr('href'),
                    method: "GET"
                }).done(function (response) {
                    var result = jQuery.parseJSON(response);
                    if(result.isGuest){
                        alert("please login");
                        return false;
                    };
                    var template = _.template($('#rate_tpl').html())({
                        rateClass: result.rated,
                        siteId: result.id
                    });

                    $(curSite).parent().html(_.template(template));


                }).fail(function () {

                });
            });
        });
                </script>

    <script type = "text/template" id = 'rate_tpl' >
                <a class = "rate btn <%= (rateClass=='rate')?'btn-primary':'btn-danger'%> " href = "/web-site/rate?id=<%= siteId %>" > <%= (rateClass=='rate')?'Rate':'Unrate'%> </a>
    </script>

frontend/views/web-site/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\WebSite */

$this->title = 'Update Web Site: ' . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Web Sites', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="web-site-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'categoryModel' => $categoryModel,
         'galleryModel' => $galleryModel
    ]) ?>

</div>